### ISSUE TITLE
can't find the  button to import

### ISSUE THREAD

**Issue by albjeremias** [newroco/DeckImportExport#4]
I'm using the latest version of nextcloud and of everything is a fresh install.. and i can't find the button to import the data from trello to deck... it says this on the README.md:

` the three dot menu will offer a new action "Import to Deck".`

what is the "three dot menu"?

**Comment by xstable** [comment]
Maybe they mean the three dots right behind your Board-Name? 
Don't know, as this app doesn't work at all for me (see https://help.nextcloud.com/t/did-someone-use-trello-to-deck/134754/7)

**Comment by xstable** [comment]
@albjeremias figured it out. 
1. Export / Download the JSON-File from Trello
2. Save it into your NextCloud "Files" Section
3. Go to that file, and click on the 3 dots behind the Filename

![image](https://user-images.githubusercontent.com/1778068/197753398-aa14a314-073b-4301-9f47-ed2805980543.png)

Then you can import it.

**Comment by albjeremias** [comment]
https://github.com/newroco/deckimportfromtrello/pull/6 <3
